title: The chalk board
description: >- # ignore newlines
This site contains helpful tips and trips and other things I've learned
over the years. This is specifically useful for Open Liberty, WebSphere
Liberty, WebSphere Application Server (WAS) and IBM MQ.
theme: minima
defaults:
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

